module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'revert',
        'build',
        'ci',
      ],
    ],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-case': [2, 'always', 'sentence-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 100],
  },
  prompt: {
    messages: {
      type: "Selecciona el tipo de cambio que estás cometiendo:",
      scope: "Indica el alcance de este cambio (opcional):",
      customScope: "Indica un alcance personalizado:",
      subject: "Escribe una descripción corta e imperativa del cambio:\n",
      body: "Proporciona una descripción más larga del cambio (opcional). Usa '|' para nueva línea:\n",
      breaking: "Enumera cualquier cambio BREAKING (opcional):\n",
      footerPrefixes: "Enumera cualquier prefijo de pie de página (opcional):\n",
      confirmCommit: "¿Confirmar el commit con el mensaje generado?",
    },
    types: [
      { value: 'feat', name: 'feat:     Una nueva funcionalidad', description: 'Añade una nueva característica' },
      { value: 'fix', name: 'fix:      Una corrección de bug', description: 'Corrige un error' },
      { value: 'docs', name: 'docs:     Cambios solo en documentación', description: 'Actualiza documentación' },
      { value: 'style', name: 'style:    Cambios que no afectan el significado del código', description: 'Formato, punto y coma, etc.' },
      { value: 'refactor', name: 'refactor: Refactorización de código', description: 'Reestructura código sin cambiar comportamiento' },
      { value: 'perf', name: 'perf:     Mejora de rendimiento', description: 'Optimiza rendimiento' },
      { value: 'test', name: 'test:     Añade o corrige tests', description: 'Tests unitarios, integración, etc.' },
      { value: 'chore', name: 'chore:    Cambios en build, deps, etc.', description: 'Mantenimiento, dependencias, tooling' },
      { value: 'revert', name: 'revert:   Revierte un commit previo', description: 'Deshace cambios' },
      { value: 'build', name: 'build:    Cambios en sistema de build', description: 'Webpack, Vite, Turbo, etc.' },
      { value: 'ci', name: 'ci:       Cambios en CI/CD', description: 'GitHub Actions, etc.' },
    ],
  },
};